"""
Django settings for election_app project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from django.conf.urls import static
from django.contrib import staticfiles

import os


SITE_URL = "http://127.0.0.1:8000"  # URL de ton site en local


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1zw!-uo=13&bkd&l8lm(m_y9tqqbdm2%@m_3053d#s7u-!u))f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECRET_KEY : Utilisation d'une clé secrète par défaut pour éviter les erreurs
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-tempkey')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ton-domaine.com']  # Ajoute ton domaine WordPress si nécessaire

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'election_app.apps.ElectionAppConfig',
    'rest_framework.authtoken',

    'rest_framework',
    'corsheaders',  # Pour gérer les requêtes entre domaines différents (CORS)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8080',
    'http://127.0.0.1:8080',  # Ajoute cette ligne pour autoriser ton frontend local
    'http://127.0.0.1:8000',  # Ajoute cette ligne pour autoriser ton frontend local


]

ROOT_URLCONF = 'election_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'election_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'electionapp',  # Nom de la base de données
        'HOST': 'localhost\SQLEXPRESS03',  # Serveur local
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Pilote ODBC
            'TrustServerCertificate': 'yes',
            'Encrypt': 'no',
            'trusted_connection': 'yes',  # Authentification Windows (pas de mot de passe)
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Etc/GMT'  # Fuseau horaire du Cameroun (UTC+1)


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Répertoire où Django va chercher les fichiers statiques
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Si vous avez un dossier 'static' dans votre répertoire racine
    
]

# Répertoire où les fichiers statiques seront collectés lors de l'exécution de 'collectstatic'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# URL publique pour accéder aux fichiers statiques
STATIC_URL = '/static/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

AUTH_USER_MODEL = 'election_app.CustomUser'
X_FRAME_OPTIONS = 'SAMEORIGIN'
# settings.py
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Chemin de base pour les fichiers téléchargés
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587  # Port sécurisé
EMAIL_USE_TLS = True  # Active TLS pour la sécurité
EMAIL_USE_SSL = False  # Désactive SSL
EMAIL_HOST_USER = "eminiantpisani@gmail.com"  # Ton adresse e-mail Outlook.com
EMAIL_HOST_PASSWORD = "lpmb eudm psnc meyh"  # Ton mot de passe Outlook.com
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',

    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Change en IsAuthenticated si besoin
    ),
}
